<a href="https://colab.research.google.com/github/MasterGino7/machine-learning-zoomcamp2025-homework/blob/main/HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
pd.__version__

'2.2.2'

In [31]:
import numpy as np

In [7]:
df=pd.read_csv("data/car_fuel_efficiency.csv")

In [8]:
df.shape

(9704, 11)

In [9]:
df.nunique()

engine_displacement      36
num_cylinders            14
horsepower              192
vehicle_weight         9704
acceleration            162
model_year               24
origin                    3
fuel_type                 2
drivetrain                2
num_doors                 9
fuel_efficiency_mpg    9704
dtype: int64

In [10]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [11]:
df.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369

In [13]:
df[df['origin']=="Asia"].describe()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,num_doors,fuel_efficiency_mpg
count,3247.000000,3099.000000,3013.000000,3247.000000,2933.000000,3247.000000,3072.000000,3247.000000
mean,200.052356,4.010326,150.303352,3006.292228,15.036754,2011.489375,-0.001628,14.973830
std,49.287252,1.971199,30.257169,502.434626,2.488340,6.704607,1.051428,2.578345
min,30.000000,0.000000,40.000000,1223.298226,6.400000,2000.000000,-4.000000,6.886245
25%,170.000000,3.000000,130.000000,2665.518985,13.300000,2006.000000,-1.000000,13.252010
50%,200.000000,4.000000,150.000000,2988.585737,15.100000,2012.000000,0.000000,15.034670
75%,230.000000,5.000000,171.000000,3345.355571,16.700000,2017.000000,1.000000,16.726318
max,370.000000,11.000000,245.000000,4661.144932,22.700000,2023.000000,4.000000,23.759123

In [14]:
df['horsepower'].median()

149.0

In [17]:
df['horsepower'].mode()

0    152.0
Name: horsepower, dtype: float64

In [19]:
df['horsepower'].fillna(152)

0       159.0
1        97.0
2        78.0
3       152.0
4       140.0
        ...
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64

In [21]:
step01 = df[df['origin']=="Asia"]

In [22]:
step02 = step01[['vehicle_weight','model_year']]

In [26]:
step03=step02.head(7)

In [27]:
step03

    vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [29]:
X = step03.values

In [33]:
XTX = np.matmul(X.T,X)

In [34]:
IXTX = np.linalg.inv(XTX)

In [39]:
y = np.array([1100,1300,800,900,1000,1100,1200])

In [42]:
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [48]:
w = np.matmul(np.matmul(IXTX,X.T),y)

In [50]:
sum(w)

np.float64(0.5187709081074016)